apiVersion: v1
kind: Pod
metadata:
  name: crash-demo
spec:
  restartPolicy: Always
  containers:
    - name: crash
      image: public.ecr.aws/docker/library/busybox:latest
      command: ["sh", "-c", "echo 'crashing now'; exit 1"]