# This rule is not used by the project chapter8 itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over apps.clientgo-learning.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: chapter8
    app.kubernetes.io/managed-by: kustomize
  name: website-admin-role
rules:
- apiGroups:
  - apps.clientgo-learning.io
  resources:
  - websites
  verbs:
  - '*'
- apiGroups:
  - apps.clientgo-learning.io
  resources:
  - websites/status
  verbs:
  - get
